name: Pack Release Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Get Commit Tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Install Dependencies & Build
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
        python -m build
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 'WebImageAPI-${{ env.RELEASE_VERSION }}-py3-none-any.whl'
